name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devops-app .

      - name: Run container test
        run: docker run -d -p 3000:3000 devops-app

      - name: wait for app
        run: sleep 5

      - name: Check app
        run: curl http://localhost:3000
